Django calendar app 추가 & media files 관련 세팅
junhee0110/DAYONE_Web pull request #14
Opened 2021-07-13 03:10 UTC by chldppwls12

resolved: #13

2021-07-13 13:36 UTC, junhee0110 commented
로컬 서버에서 실행했을때 문제 없이 작동했나요?

2021-07-13 17:11 UTC, junhee0110 requested changes
setting.py에 대한 수정은 문제는 없지만 일관성을 위한 수정입니다!
그리고 urls.py에 대한 수정은 원래 계획은 reservation이라서 수정됐으면 합니다!

저도 review기능은 처음 써봐서 이렇게 하는게 맞나 싶네요...!
혹시 코드 리뷰부분이 안보이면 연락주세요!

2021-07-13 17:11 UTC, junhee0110 commented on BackEnd/DAYONE_web/DAYONE_web/settings.py
> +    'calendarpage',
이 부분을 'calendarpage.apps.CalendarpageConfig'로 수정할 수 있을까요??
제가 Django Document 보면서 했을 때, mainpage처럼 app을 추가하라고 배웠거든요!

물론, 많은 블로그 자료 보니까 그냥 앱의 이름을 적는 것으로도 추가가 되긴 하더라고요...!
그래도 일관성있는 것이 좋을 것 같아서 'calendarpage.apps.CalendarpageConfig'로 바꿨으면합니다!

2021-07-13 17:11 UTC, junhee0110 commented on BackEnd/DAYONE_web/DAYONE_web/urls.py
> +    path('calendar/', include('calendarpage.urls')),
path를 calendar에서 reservation으로 변경해주세요!

2021-07-13 22:21 UTC, chldppwls12 commented
수정 완료했습니다!

2021-07-14 12:16 UTC, junhee0110 approved these changes
넵 확인했습니다! Merge 하겠습니다.

2021-07-14 12:16 UTC, merged