Issue#7
junhee0110/DAYONE_Web pull request #17
Opened 2021-07-17 03:19 UTC by hjhjhj00

resolved #7 
자바스크립트 기능 보완, 페이지 디자인 수정
불필요한 코드 제거 및 main 과 병합.

2021-07-17 19:13 UTC, hjhjhj00 commented
폰트 맞춤, 이전달&다음달 넘어가는 버튼 모양 변경.

2021-07-18 11:18 UTC, junhee0110 requested changes
CSS 수정바랍니다!
헤더에 버튼 위치 지정바랍니다!

2021-07-18 11:18 UTC, junhee0110 commented on FrontEnd/reservation/styles.css
> +#backButton {
Position 지정이 안되어 있습니다! mainpage 확인해서 위치 잡아주세요

2021-07-18 11:18 UTC, junhee0110 commented on FrontEnd/reservation/styles.css
> +#menuButton {
마찬가지로 Position 지정이 안되어 있습니다! 수정바랍니다

2021-07-18 11:58 UTC, hjhjhj00 commented on FrontEnd/reservation/styles.css
> +#menuButton {
아 이 부분 물어보려고 했는데, 메인페이지의 헤더 부분을 가져오지 않고, 예약페이지에서 따로 헤더부분을 만들어야 할까요? 혹시 몰라 헤더 부분 페이지 넘겨도 유지시키는 방법 찾아보고 있었습니다..!

2021-07-18 13:33 UTC, junhee0110 commented on FrontEnd/reservation/styles.css
> +#menuButton {
저도 html include기능이 장고에 있는 줄 알았는데 아니더라고요! 근데 다른 템플릿 엔진에는 있는거 같은데, 한번 알아보겠슴다!!

2021-07-22 14:40 UTC, junhee0110 commented
저번 리뷰 이후 추가 Commit이 있었는데, 어떤 변경사항이 있었나요??
Commit message에는 Header include가 되었다고 하는데, 막상 확인해보니 어디에 반영됐는지 모르겠어서요ㅠㅠ

2021-07-22 16:20 UTC, hjhjhj00 commented
> 저번 리뷰 이후 추가 Commit이 있었는데, 어떤 변경사항이 있었나요??
> Commit message에는 Header include가 되었다고 하는데, 막상 확인해보니 어디에 반영됐는지 모르겠어서요ㅠㅠ

2021-07-24 06:31 UTC, junhee0110 commented
아아아아 템플릿도 여기서 처리한 줄 알고 include된거 찾고 있었네요 ㅎㅎ..
확인했습니다!

2021-07-24 06:37 UTC, junhee0110 approved these changes
잘 확인했습니다!! merge하겠습니다!!
그런데 날짜수에 따라서 4~6주로 바뀌면서 칸 너비가 계속 바뀌는데 이 부분도 추후 개선을 해보는게 좋을것같네요

+ conflict는 제가 해결해서 merge하겠습니다

2021-07-24 06:43 UTC, merged