Add files via upload
junhee0110/DAYONE_Web pull request #49
Opened 2021-08-24 16:33 UTC by Yumin-12

마이페이지 간격 수정

2021-08-28 07:35 UTC, Yumin-12 commented
find ID find PW 탈퇴페이지 추가해서 올립니당

2021-09-02 17:49 UTC, junhee0110 requested changes
이게.. 예전 버전이 돌아오긴 했는데, 다 돌아온 게 아니여서 내가 리뷰를 달 수 없는 부분이 있넹..
너무 오래걸려서 미안해 ㅠㅠㅠ
일단 크게 문제되는 부분만 리뷰했어. 디테일한 부분은 이거 해결되면 처리해보자
+ 다음부터는 페이지 하나 작업할 떄마다 (issue 하나 처리될때마다) 풀 리퀘스트를 보내주면 너도 나도 편하고 빠르게 검토할 수 있어!

한줄 한줄 리뷰할 수 없는 부분은 여기다가 적어줄게

마이페이지/my.html 38~44줄
-> 이 부분은 a태그 하나로 처리해줄 수 있어. id도 a태그에 넣어주면 되구.
일단, 구체적으로 위치를 잡으려고 position_box class를 달아준게 보이는데, 이건 a태그 padding으로 처리해주면 돼, 그리고 border 넣어주면 박스처럼 보일 수 있겠지!

중간부터는 review를 안달았는데, 위에 언급한 문제랑 같은 문제들이라서 안달았어!
1. 굳이 필요없는 div 태그
2. 수직 중앙 정렬을 위해 line-height에 calc 사용해보기!

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/my.html
> +                <div id="profile_circle" class="row">
이 div에는 row class를 달아줄 필요는 없어!

row는 grid를 위한 컨테이너야. 여기서는 div의 내용물 하나이니까, 굳이 필요가 없징

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/my.html
> +          <div id = "reserve_confirm" class = "row">
마찬가지로 row는 여기에 달아줄 필요없어. 이거보다 하나 위에 달아줘야. "예약한 동방 확인하기"와 "동아리방 위치 확인하기"가 grid에 맞게 반응형으로 작동할거야. 근데 이 부분은 아직 디자인이 완료되지 않았으니까 신경쓰지 않아도 돼!

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/my.html
>                  <div class = "position_box">
50~57번째 줄은 a태그 하나로 처리할 수 있어!
글자의 세부 위치는 padding으로 잡으면 되고, border 속성으로 상자를 만들 수 있지

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/my.html
> +        <div id="locate_confirm" class="row">
49번째 줄과 마찬가지로 row는 여기 달아줄 필요없어

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/my.html
> +          <div class="shortcut col-12 col-md-4">
마찬가지로 67번째 줄까지는 a태그 하나로 처리할 수 있어!

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/my.html
>               <div id = "withdraw_content" class="row" >
마찬가지로 여기도 row달아줄 필요없엉

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +  top: 18.5vh;
여기 top 속성은 왜 있는거야??
position 속성이 없어서 적용이 안될거같아

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +  width:44vw;
이 부분 때문에 크기따라 원이 찌그러지는 것 같아.
그냥 단위를 px로 잡아주는 게 좋을 것 같아.

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +  height:24.6vh;
여기도 위에 줄과 마찬가지야

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
>  #profile_amendment .position_box a
html파일에서 언급한대로 a태그 하나로 줄일 수 있으니, html수정 후, 이 부분도 수정해야 할거야

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +    line-height: 20px;
아마 수직 중앙 정렬을 위해 사용한 것 같은데.
여기선 calc()를 사용하는게 좋아.
calc(height / font-size)로 해주면 어떤 상황에서도 중앙정렬이 돼

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
>  #profile_amendment .position_box h3
html 상에서 이 조건에 맞는 요소가 없는 것 같아. 아마 h3을 a로 바꾸면 될 것 같은데.. 확인해서 수정해줘

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +#reserve_confirm .position_box a
html에서 언급했듯, 이 부분을 a태그 하나로 처리할 수 있어.
그 부분을 수정하면 여기도 수정해야 할거야

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +  line-height: 50px;
위에서 언급했듯, 중앙 정렬을 위해 calc 문을 쓸 수 있어. 한 번 사용해봐!

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +  line-height: 50px;
여기도 마찬가지! calc문을 사용해봐

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/마이페이지/style2.css
> +#locate_confirm  .position_box h3
이 부분도 h3이 아니고 a로 바꿔야 할 것 같아

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/find_PW.html
> +            <div class="position_box">
굳이 div를 하나 더 추가할 필요없을 것 같아

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/find_PW.html
> +         <div class="position_box">
여기도 마찬가지로 div가 필요없을 것 같아

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/find_PW.html
> +         <p id="name_title" style="padding-left:12vw; "> 이름 </p>
p말고 label태그를 사용해도 좋을 것 같아.

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/find_PW.html
> +         <p id="ID_title" style="padding-left:12vw;"> 아이디 </p>
마찬가지로 label 태그를 사용하는 게 좋을 것 같아

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/find_PW.html
> +         <p id="number_title" style="padding-left:12vw;"> 휴대폰번호 </p>
마찬가지로 label태그!

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/find_PW.html
> +         <p id="confirm_title" style="padding-left:12vw;"> 인증번호 </p>
우리가 휴대폰 인증을 할 수 있을련지 모르겠다.. 아무튼 여기도 label 태그!

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/find_PW.html
> +      <div id ="button" class = "container">
여기서 83번째 줄까지 그냥 a태그 하나로 처리할 수 있어! 방식은 앞서 언급한 것과 같아

2021-09-02 17:49 UTC, junhee0110 commented on FrontEnd/비밀번호 찾기/style2.css
> +  line-height: 50px;
마찬가지로 calc를 사용해보장

2021-09-07 16:03 UTC, Yumin-12 commented
일단 마이페이지만 수정해봤어 나머지도 차차해서 다 해볼게

2021-09-10 15:43 UTC, Yumin-12 commented
아직 calc 안했음 근데 div 줄이는거랑 position box 태그 없애는 거 row 태그 수정 했고 그 상단에 가로 선 shadow로 넣었으.... calc 수정 필요해!!!

2021-09-10 15:43 UTC, closed without merging